name: StrideWell
description: "Frailty Care Your Way"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.2
  flutter_tts: ^4.0.2
  dropdown_search: ^6.0.1
  sensors_plus: ^6.1.0
  http: ^1.2.2
  flutter_launcher_icons: ^0.14.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/image/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/image/icon.png"
  web:
    generate: true